### ISSUE TITLE
Can the PDF version export in color?

### ISSUE THREAD

**Issue by imann24** [karlitos/KissMyResume#1]
Hi, big fan of the tool. Most effective/straightforward one I've tried so far.

I encountered a slight issue where the PDF version exports in black & white. Any guidance on how to change this?

**Comment by karlitos** [comment]
Hello @imann24 ,

many thanks for your kind feedback 😊 To your question: the PDF export should be colourful. Which Theme do you use ?

The PDF export is nothing more, than a print-to-PDF done by Puppeteer (Headless Chrome driver). How does it look like, if you try to print the CV exported to HTML ?

If the theme, you use with KissMyResume defines specific styling for printing ([my own theme](https://github.com/karlitos/jsonresume-theme-mocha-responsive) does this, so the printed output is not white-on-black 😄 ), then it's actually a feature, not a bug.

In this case you can download the theme (clone the repo, build it ...) and then change the styling according to your needs

**Comment by imann24** [comment]
Thanks very much for your response and explanation. Sounds like all I need to do to fix is specify/tweak the default theme. 

Greatly appreciate the help!
